#!/usr/bin/env bash
# Brings up an isolated teleportd + Vite dev server, reachable from a phone
# via Tailscale Serve. See README.md in this directory for the full story;
# this is the "just make it work" entry point.
#
# Safe to run on a machine that already has a live/provisioned teleportd on
# :7337 (e.g. via ~/dotfiles/components/teleport) -- this picks its own port
# and its own data dir, and never touches that instance or its data.
#
# Usage: scripts/mobile-dev/up.sh [port]
#   port: the dev daemon's own port. Defaults to 7339. Pass a different one
#   if that's also taken (check with `lsof -nP -iTCP:<port> -sTCP:LISTEN`).
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
port="${1:-7339}"
data_dir="$repo_root/.dev-data"
serve_port="${MOBILE_DEV_SERVE_PORT:-8443}"

# cargo/rustc are sometimes only reachable via the rustup toolchain dir, not
# plain PATH -- see dotfiles#13 (rustup install leaves ~/.cargo/bin/env
# unwritten on some machines). Work around it here rather than failing.
if command -v cargo >/dev/null 2>&1; then
  cargo_bin_dir="$(dirname "$(command -v cargo)")"
else
  found="$(ls "$HOME"/.rustup/toolchains/*/bin/cargo 2>/dev/null | head -1 || true)"
  cargo_bin_dir="$(dirname "${found:-/nonexistent}")"
fi
if [[ ! -x "$cargo_bin_dir/cargo" ]]; then
  echo "error: cargo not found on PATH or under ~/.rustup/toolchains/*/bin" >&2
  echo "       (see https://github.com/alehatsman/dotfiles/issues/13)" >&2
  exit 1
fi

tailnet_host="$(tailscale status --json 2>/dev/null \
  | python3 -c "import json,sys; print(json.load(sys.stdin)['Self']['DNSName'].rstrip('.'))" 2>/dev/null || true)"
if [[ -z "$tailnet_host" ]]; then
  echo "error: could not read this machine's tailnet hostname. Is 'tailscale up' done?" >&2
  exit 1
fi

if lsof -nP -iTCP:"$port" -sTCP:LISTEN >/dev/null 2>&1; then
  echo "error: :$port is already in use. Pass a different port, or it may already be up --" >&2
  echo "       check /tmp/teleportd-dev.log." >&2
  exit 1
fi

mkdir -p "$data_dir"

# daemon/src/auth.rs: the Host check strips the port before comparing, the
# Origin check requires the full string INCLUDING the port. Swap these and
# every mutating request (ws-ticket, session create/delete) 403s with
# "Origin or Host rejected" while plain GETs keep working -- a confusing,
# partially-working state that looks like the app is broken. Regenerated
# every run; don't hand-edit.
cat > "$data_dir/config.toml" <<EOF
# Generated by scripts/mobile-dev/up.sh -- regenerated on every run.
allowed_origins = ["https://$tailnet_host:$serve_port"]
allowed_hosts   = ["$tailnet_host"]
EOF

echo "==> starting teleportd (dev, isolated, :$port, $data_dir)"
( cd "$repo_root/daemon" && PATH="$cargo_bin_dir:$PATH" \
  cargo run -- --listen "127.0.0.1:$port" --data-dir "$data_dir" \
  > /tmp/teleportd-dev.log 2>&1 & )

echo "==> starting vite dev server (:5173, proxying to :$port)"
( cd "$repo_root/web" && \
  TELEPORTD_DEV_PORT="$port" TELEPORT_TAILNET_HOST="$tailnet_host" \
  npm run dev > /tmp/vite-dev.log 2>&1 & )

echo "==> waiting for teleportd to report ready"
ready=""
for _ in $(seq 1 40); do
  if grep -q "teleportd listening" /tmp/teleportd-dev.log 2>/dev/null; then
    ready=1
    break
  fi
  if grep -qE "^error|panicked" /tmp/teleportd-dev.log 2>/dev/null; then
    break
  fi
  sleep 0.5
done
if [[ -z "$ready" ]]; then
  echo "error: teleportd didn't come up in time -- check /tmp/teleportd-dev.log" >&2
  tail -20 /tmp/teleportd-dev.log >&2
  exit 1
fi

echo "==> wiring Tailscale Serve (:$serve_port -> 127.0.0.1:5173)"
tailscale serve --bg --https="$serve_port" http://127.0.0.1:5173 >/dev/null

token="$(cat "$data_dir/token" 2>/dev/null || echo "MISSING")"
echo
echo "Dev daemon (direct, no phone):  http://127.0.0.1:$port/?token=$token"
echo "Phone URL:                      https://$tailnet_host:$serve_port/?token=$token"
echo "Logs:                           /tmp/teleportd-dev.log  /tmp/vite-dev.log"
echo
echo "Next: scripts/mobile-dev/chrome.mjs (Mac Chrome, approximate) or"
echo "      scripts/mobile-dev/phone.mjs (real device via safaridriver)."
